%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
            -   master

    schedule:
        -   cron:  '6 11 * * *'
            # because 82h:66m = 3d 11h 6m

jobs:
    job_build_nodemcu_for_esp8266:
        runs-on: ubuntu-latest
        name: '[ESP8266] Make an all-defaults firmware image'
        steps:
            -   name: '[ESP8266] Check out the repo files'
                # This example repo doesn't have any files that would be used,
                # so this step is useless for the build.
                # It's only here to show how you can do it in your fork.
                uses: 'actions/checkout@v2'

            -   name: '[ESP8266] Actually build the firmware'
                uses: 'mk-pmb/nodemcu-firmware-build-as-github-action@v1'
                with:
                    firmware_branch: 'dev'
                    firmware_git_reset: 'bf8f14b6'
                    # https://github.com/nodemcu/nodemcu-firmware/issues/2993

            -   name: '[ESP8266] Upload the firmware files as artifact'
                uses: actions/upload-artifact@v1
                with:
                    name: esp8266_nodemcu_firmware
                    path: output/

    job_build_nodemcu_for_esp32:
        runs-on: ubuntu-latest
        name: '[ESP32] Make an all-defaults firmware image'
        steps:
            -   name: '[ESP32] Check out the repo files'
                uses: 'actions/checkout@v2'

            -   name: '[ESP32] Actually build the firmware'
                uses: 'mk-pmb/nodemcu-firmware-build-as-github-action@v1'
                with:
                    firmware_branch: 'dev-esp32'

            -   name: '[ESP32] Upload the firmware files as artifact'
                uses: actions/upload-artifact@v1
                with:
                    name: esp32_nodemcu_firmware
                    path: output/

...
